import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "../components/Footer";
import { ThemeContextProvider } from "../context/ThemeContext";
import Navbar from "../components/Navbar";
import ThemeProvider from "./providers/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider>
          <ThemeProvider>
            <div className="w-full  px-4 2xl:px-32 ">
              <Navbar />
            </div>
            <div className=" 2xl:px-32">{children}</div>
            {/* <Footer /> */}
          </ThemeProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
