import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "../components/Footer";
import { ThemeContextProvider } from "../context/ThemeContext";
import Navbar from "../components/Navbar";
import ThemeProvider from "./providers/ThemeProvider";
import Dashboard from "../components/Dashboard";
import AuthProvider from "./providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ThemeContextProvider>
            <ThemeProvider>
              <div className="w-full  px-4 2xl:px-32 "></div>
              <div className="lg:w-full flex gap-6">
                <div className="min-h-screen hidden xl:block w-[20%]">
                  <Dashboard />
                </div>
                <div className="w-full lg:w-[80%]">
                  <div className="">
                    <Navbar />
                  </div>
                  <div className="m-6">{children}</div>
                </div>
              </div>
              {/* <Footer /> */}
            </ThemeProvider>
          </ThemeContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
