import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "../components/Footer";
import { ThemeContextProvider } from "../context/ThemeContext";
import Navbar from "../components/Navbar";
import ThemeProvider from "./providers/ThemeProvider";
import Dashboard from "../components/Dashboard";
import AuthProvider from "./providers/AuthProvider";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ThemeContextProvider>
            <ThemeProvider>
              <div className="h-screen flex">
                {/* left */}
                <div className="dashboard w-[14%] md:w-[8%] lg:w-[16%] xl:w-[14%] p-4">
                  <Link
                    href={"/"}
                    className="flex items-center justify-center lg:justify-start gap-3 pl-8"
                  >
                    <Image
                      src={"/logo.png"}
                      alt={"logo"}
                      width={32}
                      height={32}
                    />
                    <span className="hidden lg:block">MBlog</span>
                  </Link>
                  <Dashboard />
                </div>
                {/* right */}
                <div className="wrapper w-[86%] md:w-[92%] lg:w-[84%] xl:w-[86%] overflow-scroll">
                  <Navbar />
                  <div className="m-6">{children}</div>
                </div>
              </div>

              {/* <Footer /> */}
            </ThemeProvider>
          </ThemeContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
